### ISSUE TITLE
Sensor data schema output should separate metadata from measurements

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-schema#10]
Currently we're using custom compound Postgres data types to support schema metadata output, along with measurements as GeoJSON data. These were introduced by me and were inherited from Jakarta floodgauges data schema, which itself will need addressing soon.

This approach isn't very scale-able, as it means rebuilding types in the schema if new metadata features are added etc., and also complicates debugging. It also increases data volume if locations of sensors (which are fixed?) are queried every time sensor data is retrieved. A more atomic and cleaner solution would be to have two endpoints, such as:

`/data/sensors/` (metadata)
`/data/sensors/measurements` (current measurements)

These could be linked by primary key on sensor id.

This of course does not provision for changing sensor locations in real time, but then the schema was not designed for that. We would need a further table or query to support this if it was desired.

@matthewberryman I'd like to discuss this to make CogniCity more "sensor" friendly, and to have a simple, normalized, relational modal which can easily be templated for different sensor platforms as required.

I would note however that I don't view this is a requirement of schema v3.0. This can be a feature which is included in a future 3.x release.

**Comment by matthewberryman** [comment]
@talltom 
I concur with that decision - the metadata is for essentially fixed sensors, and therefore no need to complicate the data types, and of course splitting up the API to be more atomic makes sense, to save data going unnecessarily, e.g. current measurements are only needed on user request. Can we discuss in more detail soon (within next week) on Google Hangout?

**Comment by tomasholderness** [comment]
- locations of sensors should still show on map even if there is no data.
- cc. @ojha-url

**Comment by tomasholderness** [comment]
Support for this has now be added in the schema: #b3f217a89b25fdd18b766e963c56f015a353f65c

Work continuing in other modules to push data into new schema via HTTP API.
