### ISSUE TITLE
no instance_region_code for floodgauges

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-schema#17]
The docs and cognicity-server code refer to and implement (respectively) the ability to specify a city (instance_region_code) but because there's nothing in the schema it always returns the full list of floodgauges irrespective of the city API parameter.

**Comment by tomasholderness** [comment]
Note:- requires completion of #10.

**Comment by tomasholderness** [comment]
Also note that there are only flood gauge data for Jakarta at the moment.

**Comment by tomasholderness** [comment]
This is now fixed over in the server: https://github.com/urbanriskmap/cognicity-server/tree/dev
