### ISSUE TITLE
type "max_flood_type" does not exist error when doing ./build/run.sh on a new db

### ISSUE THREAD

**Issue by abrahamq** [urbanriskmap/cognicity-schema#20]
`psql:./schema/cognicity/cognicity.functions.sql:26: ERROR:  function cognicity.rem_get_max_flood(timestamp with time zone, timestamp with time zone) does not exist `

` psql:./schema/cognicity/cognicity.functions.sql:27: ERROR:  type "max_flood_type" does not exist `

**Comment by abrahamq** [comment]
should maybe think about adding psql -v ON_ERROR_STOP=1

https://stackoverflow.com/questions/4480381/postgres-sql-fail-on-script-error

**Comment by tomasholderness** [comment]
Fixed the error (left in a drop statement that needed removing). To do error handling we'd have to bubble the error up to bash and stop the execution of run.sh.

**Comment by tomasholderness** [comment]
FYI. fixed in bfeff185113fff51aff600d63fb3b20f55a214d6
