### ISSUE TITLE
AWS RDS Ownership of PostGIS Objects is Incorrect

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-schema#39]
The schemas "tiger", "tiger_data" and "topology" (and their child objects) are owned by "rdsadmin" which means that the postgres user cannot be used with the pg_dump command as we've previously been doing to pull snapshots down from AWS. These objects should be owned by the postgres user (or equivilent group).

This is potentially due to a change in the way the PostGIS is configured by the schema setup script.

**Comment by matthewberryman** [comment]
https://gist.github.com/matthewberryman/7689766b5f94a5499d8c is the script I've been using. If you remove the `create extension ...` lines and `s/rds_superuser/postgres/g` and run it again it should set the owners correctly for your dump and (local) restore scripts.

**Comment by tomasholderness** [comment]
- note for Tom. check `ERROR:  permission denied: "RI_ConstraintTrigger_c_26657" is a system trigger
COPY 0`

**Comment by tomasholderness** [comment]
This internal trigger isn't affected system, will close.
