### ISSUE TITLE
Broward waterways are polygon format

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-schema#53]
- linestring is needed.

**Comment by ojha-url** [comment]
Decided the following: 
- check if EoC GIS team has primary canal linestrings available, 
- retain polygons for now in DB, while
- changing the table and endpoint names to (options):
  - [ ] canals
  - [ ] canal_segments 
  - [ ] water_control_units (original terminology in SFWMD Arc Hydro Enhanced Database*)

*Ref (pg 49): https://www.sfwmd.gov/sites/default/files/documents/ahed%20data%20dictionary.pdf
